### PR TITLE
data grid fix for bind-hidden not calling hidden callback in all scen…

### PR DESCRIPTION
**Pull request by segfault-**
…arios

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The PR is submitted to the correct branch (`dev`).
- [x] My code follows the code style of this project.
- [x] I've added relevant tests.

### CODE REVIEW

**Comment by segfault-** [comment]
hello, hopefully I submitted this PR correctly this time.  let me know if you have any questions or concerns or required changes

**Comment by tjscience** [comment]
Can you post a try where you show the problem with the current implementation?

**Comment by segfault-** [comment]
https://try.mudblazor.com/snippet/QaccOobfiQqvyErS

click on the column editor, and try to toggle visibility

**Comment by tjscience** [comment]
I see that as kind of by design. You are binding the Hidden Parameter to the property of your choosing. It makes sense then, that you would control whether the column is hidden or not through this property. If you do not bind, you get the result you are after: https://try.mudblazor.com/snippet/maGcaevfiHPowscB

Essentially, binding trumps the ability for the user to hide/show through the column chooser, which is advantageous in many ways.

**Comment by segfault-** [comment]
in it's current form, I agree, binding trumps the ability for the user to hide/show through the column chooser, however, the user could still hide the column via the discrete column "hamburger" (by clicking hide)  then the column is hidden with no way to restore visibility.  The code for the column "hamburger" updates the 2-way binding via callback.  I guess that was the point of my PR: to make the column chooser a 2-way binding via callback (so they could restore visibility).  If the devs don't want a user to be able to toggle the visibility of certain columns, I would assume they could set the column Hideable property to false.

**Comment by tjscience** [comment]
I see what you mean and will merge this. Can you take a look at the failing test though? 

 DataGridColumnChooserTest
   Source: DataGridTests.cs line 1341
   Duration: 539 ms

  Message: 
Expected dataGrid.FindAll(".mud-table-head th").Count to be 1, but found 2.

**Comment by segfault-** [comment]
updated.

**Pull request merged**
