### PR TITLE
MudDataGrid: Enable multi-column sort

### PR DESCRIPTION
**Pull request by TobiasBreuer**
## Description
This enables multi-column sorting on the DataGrid component

## How Has This Been Tested?
Unit-Tests and visual / manual testing during development

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Preview
multiSort

## Checklist:

- [x] The PR is submitted to the correct branch (`dev`).
- [x] My code follows the code style of this project.
- [x] I've added relevant tests.

### CODE REVIEW

**Comment by TobiasBreuer** [comment]
Hi @tjscience,

today I had some time again to do some stuff here.

First I just wanted to see how far I could get with that and play around a little more - now it turns out that 80 % of the work would actually be done.
Please review and let me know what you think.
If you like it, I would go the remaining 20 % (i.e. fix and extend the existing tests and also make sure that server-side loading works as expected).

Best regards!
Tobias

**Comment by tjscience** [comment]
Hi @TobiasBreuer, I will take a look and let you know. Thanks!

**Comment by tjscience** [comment]
Hi @TobiasBreuer. This looks great so far! The only issue I see, and maybe you are aware of this already, is that there is no longer a Parameter on Column to provide a custom SortBy function.

**Comment by TobiasBreuer** [comment]
Glad you like it!
Regarding the parameter on the column you are absolutely right of course. 
I removed it initially because I was focused on the grid part and thought we should not have two ways in the API to define the `SortBy` for a column (i.e. the parameter and the `SetSortAsync(...)` method on the grid).

However, the use case to define the `SortBy` func per column in the template part on integration level is for sure more intuitive and clean.
I've just pushed some changes that re-add this parameter, also I've updated the test to make use of it and sort the 'Misc' column by length instead of by content.

All tests have been updated to the new functionality. 
Based on that, I would consider this part as done - so feel free to finally review whenever you find the time😉

**Comment by TobiasBreuer** [comment]
@tjscience: One thing I noticed though during development:
Within the template of the MudDataGrid we access the `CurrentPageItems` property of the class multiple (actually four) times.
Due to the fact that this property forwards to `FilteredItems` which filters and calls the `Sort()` method, we actually filter and sort the same data four times for one rendering. 
So here is some room for optimization - Do you want to track this in a separate ticket?

**Comment by tjscience** [comment]
@TobiasBreuer, good point on the optimization of accessing CurrentPageItems, FilteredItems and calling the Sort() method. You can open a separate pull request if you would like to work on it. Much appreciated btw. I will have a look through your changes and merge shortly unless I have any questions/comments. Thanks again!

**Comment by tjscience** [comment]
I am receiving this error when sorting any column in the advanced data grid example:

image

**Comment by TobiasBreuer** [comment]
Hmm, let me check...

**Comment by tjscience** [comment]
Also, I think that there should be a way to turn this off. For example, consider the scenario where an API method only accepts one column to be sorted a ta time.

**Comment by TobiasBreuer** [comment]
Regarding the Exception: The Select-Column of course doesn't have the `Field` property set, so this is null.
Will add a check to prevent this from happening.

Regarding the control of selection. I would propose to go with a selection mode enum on grid level (None, Single, Multiple) and on column level one can just decide (as it is now) to individually allow or disable sorting by setting the `Sortable` parameter. What do you think?

**Comment by tjscience** [comment]
Got it. Yeah, that sounds like a good approach. Maybe we can just replace the Sortable parameter with SortMode on the MudDataGrid. There is no sense in having 2 parameters to handle turning sort on/off and changing the mode. Leaving it on the Column makes sense.

**Comment by TobiasBreuer** [comment]
`Maybe we can just replace the Sortable parameter with SortMode on the MudDataGrid.` Yes, that was the idea 😉 
I'll see if I have time to finish that today, but latest by tomorrow I'll push another update.

**Comment by TobiasBreuer** [comment]
Hey @tjscience: As discussed yesterday, I added the SortMode enum property on GridLevel replacing the former boolean flag.
I've also added a dedicated section to the docs to explain the sort behaviour and different modes.
Last but not least, I changed the template to resolve the current page items only once, avoiding the aforementioned multiple calls to filter and sort in the code behind.
As always: Let me know if there is something which you don't like or would like to be changed/enhanced.
Best regards!

**Comment by TobiasBreuer** [comment]
Fixed the failing test. Actually this happened, because I set the `SortMode` to be `SortMode.Multiple` per default while before, sorting was off per default. what would you prefer? 
IMHO in > 95% of the cases you want users of a grid to be able to sort the content but that's just my 2 cent. We could also argue that per default `SortMode` is set to `None` and you have to opt-in for this feature...

**Comment by tjscience** [comment]
I am fine with defaulting the sort to SortMode.Multiple. Thanks for adding the docs section. It is clean and clear which makes the new sorting functionality easy to understand. Let me know if you would like to work on anything else in phase 3. The help is much appreciated and you obviously know what you are doing. If you do take on anything else, please be sure to PR to the datagrid_phase3 branch. That is where all of the current work is being done.

**Comment by TobiasBreuer** [comment]
Yes sure, shall I rebase and re-target this PR also onto the phase-3 branch?

**Comment by tjscience** [comment]
If it is not too much trouble, that would be great.

**Comment by TobiasBreuer** [comment]
Regarding the other work, I would be interested in working on the resize feature - however I only have a very rough solution sketch for that in the back of my mind at the moment so I am far from being able to give any estimation...
Also I roughly checked inside existing solution and it seems that part of the required JS Interop is prepared in `ResizeObserver` and `ResizeListenerService` which I need to take a closer look at to understand the intended use of those.
For sure JSInterop will be required for that feature and I don't want to introduce something that is against the original design approach of the owners...

**Comment by TobiasBreuer** [comment]
Hmm okay, after rebase build is failing as it cannot find "HideMenuItem" Property on the grid instance. I currently can't seem to find the culprit. In the changeset it is not visible that I removed such a property from the grid... I'll check again tomorrow.

**Comment by tjscience** [comment]
I can try to fix that.

**Pull request merged**
